### ISSUE TITLE
Images across the post are not loading

### ISSUE THREAD

**Issue by lmitelman** [lvvittor/lvvittor.github.io#57]
## Affected post

https://www.lucasvittor.com/a-soft-introduction-to-the-zkml-rabbit-hole/

## Recommended fix, suggestions

I would like to bring to your attention an issue I encountered on [_A soft introduction to the zkML rabbit hole_
](https://www.lucasvittor.com/a-soft-introduction-to-the-zkml-rabbit-hole/) post. It appears that several images across the post are not loading, and instead, the `alt` text is being displayed.

PS: Let's grab a coffee and chat about writing articles sometime! 🙌🏻

## Screenshots
![Screenshot 2024-01-14 at 11 07 21](https://github.com/lvvittor/lvvittor.github.io/assets/44504618/fb9afa49-95f2-47e5-be58-567403b96d3b)
![Screenshot 2024-01-14 at 11 12 04](https://github.com/lvvittor/lvvittor.github.io/assets/44504618/a205c76a-20e7-4f15-a04f-e33036a6f90e)

**Comment by lvvittor** [comment]
Thanks for the issue! Images were broken because I changed the cicd pipeline (it was using an old dependency with a hard-coded version of ruby that was throwing an error for this). 

So, I updated the pipeline with the recommended practices for GitHub Actions in [this commit](https://github.com/lvvittor/lvvittor.github.io/commit/20ca7a1cd0879ff17d3c3ca9b15ac55b0777faab). 

This was what broke the images since I'm using a Jekyll plugging called  [jekyll-postfiles](https://github.com/nhoizey/jekyll-postfiles#compatibility) and it's not compatible with Github Pages (because it's a third party plugin).

The fix was to change my host provider from Github Pages to Vercel.

![image](https://github.com/lvvittor/lvvittor.github.io/assets/24721312/01aed3d4-235e-4c42-be9b-337ccf6d0c22)

You should see the fix in all posts now, but if you don't let me know! (possibly you need to wait some time for the DNS to propagate correctly)
